# using sklearn for multi regression

In [1]:
# importing libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')

In [2]:
# reading data

data = pd.read_csv('multisat.csv')

In [3]:
data

SAT   GPA  Rand 1,2,3
0   1714  2.40           1
1   1664  2.52           3
2   1760  2.54           3
3   1685  2.74           3
4   1693  2.83           2
..   ...   ...         ...
79  1936  3.71           3
80  1810  3.71           1
81  1987  3.73           3
82  1962  3.76           1
83  2050  3.81           2

[84 rows x 3 columns]

In [4]:
x = data[['SAT','Rand 1,2,3']]

In [5]:
x

SAT  Rand 1,2,3
0   1714           1
1   1664           3
2   1760           3
3   1685           3
4   1693           2
..   ...         ...
79  1936           3
80  1810           1
81  1987           3
82  1962           1
83  2050           2

[84 rows x 2 columns]

In [8]:
x.shape

(84, 2)

In [9]:
y = data[['GPA']]

In [11]:
y

GPA
0   2.40
1   2.52
2   2.54
3   2.74
4   2.83
..   ...
79  3.71
80  3.71
81  3.73
82  3.76
83  3.81

[84 rows x 1 columns]

In [12]:
# using sklearn for linear multi regression

from sklearn.linear_model import LinearRegression

In [14]:
model = LinearRegression()

In [15]:
model

LinearRegression()

In [17]:
model.fit(x,y)

LinearRegression()

In [18]:
# value of intercept --> b0
model.intercept_

array([0.29603261])

In [20]:
# value of slope_1 coeff --> b1, b2
model.coef_

array([[ 0.00165354, -0.00826982]])

In [21]:
# value of R-squared
model.score(x,y)

0.4066811952814282

In [22]:
r2 = model.score(x,y)

In [23]:
r2

0.4066811952814282

### to find adjacnt R-square value

In [27]:
n=84   # n--> no. of observations
p=2    # p--> no.of idependent variables
adjr2 = 1-(1-r2)*(n-1)/(n-p-1)  # formula for finding adjacent R-square value
print(adjr2)  # printing adj. R-square value

0.39203134825134


In [26]:
adjr2

0.39203134825134

In [29]:
# for prediction
test = pd.DataFrame([[1900,2],[1600,1]])

In [30]:
test

0  1
0  1900  2
1  1600  1

In [33]:
model.predict(test)

array([[3.42122239],
       [2.93342967]])